default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username: username
  password: password

development:
  <<: *default
  database: action_cable_crud_development

production:
  <<: *default
  database: action_cable_crud_production
